import type { Locale } from '@/lib/i18n';

const uiStrings = {
  fr: {
    skipLink: 'Aller au contenu',
    menuButton: 'Ouvrir le menu',
    menuClose: 'Fermer le menu',
    mobileMenu: 'Menu principal',
    mainNav: 'Navigation principale',
    legalNav: 'Informations légales',
    copyright: '© {year} Frédéric Lejour',
    languageSwitch: 'Langue',
    pendingTitle: 'Cette page est en préparation',
    pendingIntro:
      'Cette page est en cours de préparation. En attendant, vous pouvez consulter la version française.',
    pendingLink: 'Voir la version française',
    demoTitle: 'Démonstration du design system',
    demoSubtitle: 'Contenu provisoire — Phase 2',
    demoIntro:
      'Cette page sert à valider la direction visuelle, la hiérarchie typographique, les composants réutilisables et la navigation bilingue avant rédaction des contenus définitifs.',
    sectionPalette: 'Palette',
    sectionTypography: 'Typographie',
    sectionButtons: 'Boutons',
    sectionCards: 'Cartes',
    sectionBadges: 'Badges',
    sectionLinks: 'Liens',
    sectionSeparators: 'Séparateurs',
    sectionNavigation: 'Navigation',
    labelPrimary: 'Primaire',
    labelSecondary: 'Secondaire',
    labelText: 'Texte',
    labelLarge: 'Grand',
    labelDefault: 'Défaut',
    labelMuted: 'Muté',
    labelOutline: 'Contour',
    labelAccent: 'Accent',
    labelLight: 'Clair',
    labelDark: 'Sombre',
    labelGold: 'Or',
    labelTaupe: 'Taupe',
    labelCurrentPage: 'Page actuelle',
    wordmark: 'Frédéric Lejour',
    tagline: 'Business Development • Relations stratégiques • Growth',
  },
  de: {
    skipLink: 'Zum Inhalt springen',
    menuButton: 'Menü öffnen',
    menuClose: 'Menü schließen',
    mobileMenu: 'Hauptmenü',
    mainNav: 'Hauptnavigation',
    legalNav: 'Rechtliche Informationen',
    copyright: '© {year} Frédéric Lejour',
    languageSwitch: 'Sprache',
    pendingTitle: 'Diese Seite ist in Vorbereitung',
    pendingIntro:
      'Diese Seite wird derzeit vorbereitet. Bis dahin können Sie die französische Version besuchen.',
    pendingLink: 'Französische Version ansehen',
    demoTitle: 'Designsystem-Demo',
    demoSubtitle: 'Vorläufiger Inhalt — Phase 2',
    demoIntro:
      'Diese Seite dient der Validierung der visuellen Richtung, der typografischen Hierarchie, der wiederverwendbaren Komponenten und der zweisprachigen Navigation vor der Erstellung der endgültigen Inhalte.',
    sectionPalette: 'Farbpalette',
    sectionTypography: 'Typografie',
    sectionButtons: 'Schaltflächen',
    sectionCards: 'Karten',
    sectionBadges: 'Abzeichen',
    sectionLinks: 'Links',
    sectionSeparators: 'Trennlinien',
    sectionNavigation: 'Navigation',
    labelPrimary: 'Primär',
    labelSecondary: 'Sekundär',
    labelText: 'Text',
    labelLarge: 'Groß',
    labelDefault: 'Standard',
    labelMuted: 'Gedämpft',
    labelOutline: 'Umriss',
    labelAccent: 'Akzent',
    labelLight: 'Hell',
    labelDark: 'Dunkel',
    labelGold: 'Gold',
    labelTaupe: 'Taupe',
    labelCurrentPage: 'Aktuelle Seite',
    wordmark: 'Frédéric Lejour',
    tagline: 'Business Development • Strategische Beziehungen • Growth',
  },
  en: {
    skipLink: 'Skip to content',
    menuButton: 'Open menu',
    menuClose: 'Close menu',
    mobileMenu: 'Main menu',
    mainNav: 'Main navigation',
    legalNav: 'Legal information',
    copyright: '© {year} Frédéric Lejour',
    languageSwitch: 'Language',
    pendingTitle: 'This page is in preparation',
    pendingIntro:
      'This page is currently being prepared. In the meantime, you can visit the French version.',
    pendingLink: 'View the French version',
    demoTitle: 'Design system demo',
    demoSubtitle: 'Provisional content — Phase 2',
    demoIntro:
      'This page is used to validate the visual direction, typographic hierarchy, reusable components and multilingual navigation before the final content is written.',
    sectionPalette: 'Palette',
    sectionTypography: 'Typography',
    sectionButtons: 'Buttons',
    sectionCards: 'Cards',
    sectionBadges: 'Badges',
    sectionLinks: 'Links',
    sectionSeparators: 'Separators',
    sectionNavigation: 'Navigation',
    labelPrimary: 'Primary',
    labelSecondary: 'Secondary',
    labelText: 'Text',
    labelLarge: 'Large',
    labelDefault: 'Default',
    labelMuted: 'Muted',
    labelOutline: 'Outline',
    labelAccent: 'Accent',
    labelLight: 'Light',
    labelDark: 'Dark',
    labelGold: 'Gold',
    labelTaupe: 'Taupe',
    labelCurrentPage: 'Current page',
    wordmark: 'Frédéric Lejour',
    tagline: 'Business Development • Strategic relationships • Growth',
  },
} as const;

export type UIKey = keyof (typeof uiStrings)['fr'];

export function ui(locale: Locale, key: UIKey): string {
  return uiStrings[locale][key];
}

export function uiWithYear(locale: Locale, key: 'copyright', year: number): string {
  return uiStrings[locale][key].replace('{year}', String(year));
}
